### PR TITLE
Mega PR

### PR DESCRIPTION
**Pull request by Anutha02**
This PR contains all of the changes of #654 , #660 , #661 , #662 , #663 . Plus some other small tweaks. Basically the merge order of the above PRs destroys the library, so I have created this PR that solves the merge issues. Review the above mentioned PRs and suggest changes, they will be added to this PR. We have to merge only this PR instead of the above mentioned 5.

### CODE REVIEW

**Comment by cortinico** [comment]
Hey @Anutha02 
Thanks for your hard work.

My apologize but I'm not willing to merge this PR.
Pull request should be self-contained and have a specific topic. Honestly having a PR with a name "Mega PR" is not really helpful.

Other developers will find this PR and won't be able to really understand what is this about.

Can I ask you to split this into smaller PRs that are not _destroying_ the library? Please send a PR for just a specific fix/feature. 

Moreover, the smaller the PR is the better. Bigger PRs are hard to review and their likelihood of being merged is just too small. This one is extremely big:  +1,428 −329.

**Comment by cortinico** [comment]
Can you also tell me what should I do with the other PRs? Now they're all marked as `[DO NOT MERGE]`. Can I close them?

**Comment by Anutha02** [comment]
@cortnico Well, I guess I have only one choice...
Don't close them, but review and merge only in the order specified here:


This is the correct merge order: fix-swipe->new-activity->new-fragment->simple-parallax->minor fixes. This should give you the minimum number of merge conflicts

**Comment by Anutha02** [comment]
I have switched to consistently using title instead of heading all over the library, so that would be a conflict. Please tell me if any other merge conflicts require my attention.

**Pull request closed without merging**
