### PR TITLE
Basic Androidx navigation component support

### PR DESCRIPTION
**Pull request by oliexdev**
regarding to issue #801 I implemented a basic support for the new Androidx navigation component, so that an app can set a navigation graph and navigate to another fragment (outside of the AppIntro activity)

This PR is **not** merge ready!

This should show only the basic principle for an navigation sample.

What still have to be done is the following:

- Separate AppIntro class into a AppNav class and a AppInto fragment. The AppNav class should only contain the general layout (like toolbar and so on). The AppIntro fragment should contain the ViewPager. This fragment could be the default fragment which is shown into the NavFragment.
(Currently in this PR for a simplification I divide the screen one half for the NavFragment and the lower part for the ViewPager)

- Convert the current Java classes into Kotlin (Sorry I never used Kotlin before, so I programmed in Java)

- Currently, I didn't found a solution that the SafeArgs method works but you could pass Arguments with the Bundle method to another Fragment

If you have any question, please feel free to ask me. I will try to answer them.

### CODE REVIEW

**Comment by cortinico** [comment]
Thanks for the PR @oliexdev, really appreciate.
There are several points that should be discussed:

> Separate AppIntro class into a AppNav class and a AppInto fragment

Adding another layer to the view hierarchy seems like not the best approach. We currently already have an Activity and several fragments in the ViewPager. Adding another intermediate Fragment just to support the Navigation library seems not really worth to me.

Ideally the whole Navigation integration should be isolated inside an `appintro-navigation` module and it should be optional. I don't even know if this is achievable at the current status.

> so that an app can set a navigation graph and navigate to another fragment (outside of the AppIntro activity)

If I understand correctly, you just want to navigate outside of a specific slide of the AppIntro. Can't you just `startActivity` there with the activity you want to start.

I feel the real benefit of providing a potential navigation integration is that developers can deep-link inside a specific page of the AppIntro (so the opposite of your use case). That would require that navigation destination are generated properly for every slide, etc.

I don't know how much effort would be to develop such solution, but it feels to me that currently it's probably not worth the time. 

Side note: the PR is also not building so I wasn't really able to give it a try.

**Comment by oliexdev** [comment]
> Adding another layer to the view hierarchy seems like not the best approach. We currently already have an Activity and several fragments in the ViewPager. Adding another intermediate Fragment just to support the Navigation library seems not really worth to me.
> 
> Ideally the whole Navigation integration should be isolated inside an appintro-navigation module and it should be optional. I don't even know if this is achievable at the current status.

Sure that's a design decision which is up to the maintainer. I never worked before with gradle modules, so I can't really help in this goal.

> If I understand correctly, you just want to navigate outside of a specific slide of the AppIntro. Can't you just startActivity from there with the activity you want to start.
> 
> I feel the real benefit of providing a potential navigation integration is that developers can deep-link inside a specific page of the AppIntro (so the opposite of your use case). That would require that navigation destination are generated properly for every slide, etc.
> 
> I don't know how much effort would be to develop such solution, but it feels to me that currently it's probably not worth the time.

Not really as in issue #801 described it would break the navigation component in the main app because it is recommend to have only one activity and the other UI are fragments. So you can jump out with startAcitivty but only if you wrap the other fragments within another activity in the main app as I did in my current workaround implementation at commit https://github.com/oliexdev/openScale/commit/83e55e05bc9d93f4ba4df7a64b3a44b8b70710b1
But with this you break the navigation component features. Normally you can navigate directly to a fragment with optional safeArgs and other features which comes with Androidx. If you want to jump into an AppIntro activity (the other way around) with the navigation component that is already possible but idk how to select a specific slide in the AppIntro.

> Side note: the PR is also not building so I wasn't really able to give it a try.

The build error were in your original code, see https://github.com/AppIntro/AppIntro/pull/810/commits/d4b8b5b1ed0a436a1ca2c6d173773371f7d8f56a but I fixed it. :wink:

**Comment by cortinico** [comment]
> Not really as in issue #801 described it would break the navigation component in the main app because it is recommend to have only one activity and the other UI are fragments.

Can you elaborate more here? I don't see how not supporting Navigation in AppIntro will break your app. I understand that is recommended to follow a single activity approach but that's not required, especially if you rely on third party libraries such as AppIntro

**Comment by oliexdev** [comment]
I am sorry, I think I can't elaborate it more as I wrote:

> So you can jump out with startAcitivty but only if you wrap the other fragments within another activity in the main app as I did in my current workaround implementation at commit oliexdev/openScale@83e55e0
> But with this you break the navigation component features. Normally you can navigate directly to a fragment with optional safeArgs and other features which comes with Androidx. If you want to jump into an AppIntro activity (the other way around) with the navigation component that is already possible but idk how to select a specific slide in the AppIntro.

What in detail you don't understand? Maybe you see it better if you try by yourself to navigate outside AppInto to an already existing fragment outside AppInto which use Androidx navigation component? I think the use cases that you have to jump out of AppIntro activity for e.g. to create a user is not low.

**Comment by cortinico** [comment]
> I think the use cases that you have to jump out of AppIntro activity for e.g. to create a user is not low.

I see your point. Unfortunately AppIntro doesn't support this and we're probably not going to support it.

Our API is already quite extensive, and supporting navigating outside of a started AppIntro is currently not supported.

Moreover, you're the first user requesting this feature so far.

**Comment by oliexdev** [comment]
no problem I can fully understand that this feature is too troublesome to implement and maintain if I am the only one with this use case. I can live with my current workaround solution.

**Comment by cortinico** [comment]
> no problem I can fully understand that this feature is too troublesome to implement and maintain if I am the only one with this use case.

Thanks anyway for the contribution. 
We will keep issue #801 opened so if someone else has a similar setup as yours and want to try a different approach, we can re-discuss it 👍

**Pull request closed without merging**
