### PR TITLE
Prepare release 6.2.0

### PR DESCRIPTION
**Pull request by cortinico**
Time to prepare a new release 🎉 Here the release notes

### CODE REVIEW

**Comment by cortinico** [comment]
`lint` is fixed by #958

**Comment by nicolabeghin** [comment]
Following

**Review by paolorotolo — COMMENTED** [review]
Looks good, let's see if we can land https://github.com/AppIntro/AppIntro/pull/979 in this too. I'm testing it now.

**Comment by cortinico** [comment]
Are we missing anything else for 6.2?

**Comment by paolorotolo** [comment]
After merging #984 we're good to go for me!

**Comment by cortinico** [comment]
I'd like to have this one merged https://github.com/AppIntro/AppIntro/pull/964

**Comment by cortinico** [comment]
This should be (finally) ready to go on Monday :)

**Review by paolorotolo — APPROVED** [review]
Looks good! Is there anything else I can do for Monday's release?

**Comment by cortinico** [comment]
> Looks good! Is there anything else I can do for Monday's release?

Nope, let's just avoid releasing over the weekend so we can follow up if there are problems

**Pull request merged**
