### PR TITLE
Update Dependencies

### PR DESCRIPTION
**Pull request by AnuthaDev**
Update ktlint to 9.1.1
Update detekt to 1.4.0
Update target&compile sdk to 29
Update appcompat to 1.1.0
Update kotlin stdlib to 1.3.61
Updated detekt-default-config file
Fix code to be compliant with ktlint and detekt
Altered PagerAdapter to simplify code and solve error

### CODE REVIEW

**Comment by AnuthaDev** [comment]
Hey @cortinico ktlintCheck is giving some errors regarding missing braces for single line if expressions. Should I add the braces or is there a way to suppress those errors??

**Comment by AnuthaDev** [comment]
Ideally this should be merged before #686

**Comment by cortinico** [comment]
> Hey @cortinico ktlintCheck is giving some errors regarding missing braces for single line if expressions. Should I add the braces or is there a way to suppress those errors??

The build is actually failing as you need to update the travis file if you bump the compileSdkVersion to 29.

Regarding `ktlintCheck`, please update all the code to make it compliant with the new checks.

**Comment by AnuthaDev** [comment]
Hey @cortinico Please take a look. I have fixed the build.

**Pull request merged**
