### PR TITLE
[WIP] Add Navigation Bar Translucency

### LINKED ISSUE #740: Add possibility to change navbar color per slide
Hi, I'm creating an IntroSlider using this library and I want to do something which is not apparently possible.
I have the following intro:
demo

You can see that the color of the navigation bar doesn't changes, what creates kind of a visual disturbance. 

**What solution I'd like*
Add possibility to change navbar color per slide, e.g like this:
```kotlin
val page1 = SliderPage(
                title = "Title!",
                description = "Description!",
                bgColor = Color.parseColor("#669900"),
                imageDrawable = R.drawable.ic_traveling,
                systemNavbarColor = Color.parseColor("#669900")
        )
```

### PR DESCRIPTION
**Pull request by AnuthaDev**
Fixes #740 
Added the option to have translucent navigation bars.

Currently the landscape layout is buggy

### CODE REVIEW

**Comment by AnuthaDev** [comment]
Hey @cortinico So, I have pieced together this solution, it works!! But the code is ugly and I am not good at coding, so I hope you will be able to make something useful out of it

**Comment by cortinico** [comment]
Thanks for the contrib @AnuthaDev 
I'll try to get over this after the release.
In the meanwhile can I ask you to please make Travis green?

**Comment by AnuthaDev** [comment]
Hey @cortinico Just a gentle reminder that you need to adopt this PR 😉 ('cuz I won't have access to my PC for several more months)

**Comment by cortinico** [comment]
Closing this as the feature is not really requested as of today and it will introduce too much complexity on the API right now.

**Pull request closed without merging**
