### PR TITLE
Prepare AppIntro 6.0.0

### LINKED ISSUE #725: Preparing AppIntro 6.0.0 Stable
Let's use this issue to keep track of the things we need to do before releasing AppIntro 6.0.0

If you have the feeling you have a feature or a fix that is worth being included in the upcoming release, please comment here asap.

To give an ETA: ideally we should be able to release 6.x within the next 2/3 weeks.

- [x] Merge #686 / #730 
- [x] Prepare a Release note document
- [x] Prepare a migration document from 5.x.
- [x] Update the screenshots on the README
- [x] Update the README to have examples of the newer API
- [x] Update the README from Java to Kotlin
- [x] Bump all the third party dependencies (Kotlin, Gradle, Support lib, etc.)

### PR DESCRIPTION
**Pull request by cortinico**
Let's get ready for the upcoming stable release of AppIntro.
~I've added release notes to this PR. Will update the README in the following days.~

This PR contains all the material for AppIntro 6.0.0.
The diff looks huge as we have a SVG/AI file that are treated as text. It's not that big actually.

Specifically this PR will
- Update the README
- Update the screenshots
- Remove the `/javadoc` old folder
- Add Release notes for the upcoming version
- Add a migration document with the Api changes from 5.x to 6.x

It should be merged once #770 #767 #773 #774 #775 #776 are also merged.

Fixes #725

### CODE REVIEW

**Comment by AnuthaDev** [comment]
Hey @cortinico I believe #733 , #734  and #735 should be merged before 6.0 release.

**Comment by paolorotolo** [comment]
Very nice work, I'll see if I can update the example app as well before release.

**Comment by cortinico** [comment]
@paolorotolo This is now ready on my end 🎉 
Feel free to review the README and the other documentation.

I feel that at a certain point we should move to something like mkdocs or so to have a shorter README and a more organised documentation.

Let's merge it on Monday next week + do the release if there are no other blockers.

**Comment by paolorotolo** [comment]
Thanks a lot @cortinico, it looks perfect.
Ok it's fine for me to release next Monday, if no other issues pop out :+1: 

Thanks again.

**Comment by cortinico** [comment]
> I would move the Migrating section right above the Features, since probably most users will upgrade from an older version.

Yup done.

> move the logo to the end of readme or move it on the same row of the first AppIntro gif (so it will not waste vertical space).

I'm trying this and have logo/gif side by side.

**Comment by cortinico** [comment]
Also @paolorotolo two minor things:

* In the new README there is no mention for this video https://www.youtube.com/watch?v=-KgAAbZz248. I would love to keep it as it's part of the library heritage. What do you think?

* The section at the bottom contains a spoiler with all the app using AppIntro. With that I suggest we close #325 and we just invite people to open a PR agains the README. What do you think?

**Comment by paolorotolo** [comment]
Sorry just noticed the last message. I don't know, that video is very old and deprecated I guess...
If you're ok with it, let's move the discussion about App using AppIntro on another issue. Some links in README are fine too, but I'm wondering if there's a better way to handle this.

**Pull request merged**
